version: '2'
services:
  omniwagtailevents:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./:/src"
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
